default_agent: plant_watering
agents:
  plant_watering:
    name: plant_watering
    language: python
    node_version: '20'
    entrypoint: /Users/jun/Documents/2026/plant-watering/agent/src/app.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/jun/Documents/2026/plant-watering/agent
    aws:
      execution_role: arn:aws:iam::533267235251:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-f5aba8d61d
      execution_role_auto_create: false
      account: '533267235251'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-533267235251-us-west-2
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: plant_watering-0u0rMsAxuN
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:533267235251:runtime/plant_watering-0u0rMsAxuN
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
